### ISSUE TITLE
`runError` should use a forall to put its exception type first.

### ISSUE THREAD

**Issue by patrickt** [robrix/fused-effects#100]
Right now, the `runError` function puts `sig` and `m` before `exc` in its list of type parameters. This can lead to unpleasantly periphrastic invocations of `runError`:

```haskell
runError @_ @_ @FatalException
```

I propose we add an explicit `forall` that places the `exc` at the head of the list, rendering the above
```haskell
runError @FatalException
```

I think this keeps with our ethos of “most important type variables first”, but it would be a backwards-incompatible change. Thoughts?

**Comment by robrix** [comment]
@patrickt fixed this in #103.
