### ISSUE TITLE
Document a list of useful default extensions

### ISSUE THREAD

**Issue by kwf** [robrix/fused-effects#56]
Splitting this out as a todo ticket from discussion in #55:

> Perhaps it would be good to have a list in the docs of language extensions you'll probably need to enable to use this library. In general, I think this is a useful kind of documentation, which I haven't seen in many libraries. While Hackage lists the language extensions necessary to implement a library, it doesn't have a mechanism to directly document which ones you need as an end-user of the library (and for what purposes).

**Comment by robrix** [comment]
Fixed in https://github.com/robrix/fused-effects/pull/59
