### ISSUE TITLE
An interesting use of reflection

### ISSUE THREAD

**Issue by mitchellwrosen** [robrix/fused-effects#57]
I was playing around with `fused-effects` a bit (basically just trying to understand it), and it occurred to me that it might work very nicely with `reflection`.

For example, I was designing a simple logging effect, but when it came time to define a carrier for it, I felt I had to make some arbitrary choice about what to do with the message to log.

Since each carrier requires is a separate instance of a type class, this is quite a lot of boilerplate just to get different behaviors.

I noticed this pain as well in `fused-effects`, with three different trace carriers `TraceByReturningC`, `TraceByPrintingC`, and `TraceByIgnoringC`. In particular, `TraceByPrintingC` and `TraceByIgnoringC` could be combined into one `TraceC` like so:

```haskell
-- Note: phantom 's'
newtype TraceC s m a = TraceC { runTraceC :: m a }

-- Note: Reifies
instance (Monad m, Carrier sig m, Reifies s (String -> m ())) => Carrier (Trace :+: sig) (TraceC s m) where

-- Note: user supplies the trace function, it is not tucked inside an instance
runTrace 
  :: (Monad m, Carrier sig m) 
  => (String -> m ()) 
  -> (forall s. Eff (TraceC s m) a) 
  -> m a
runTrace f m = reify f (\(_ :: Proxy s) -> runTraceC (interpret (m @s))
```

Anyways, that's as far as I got, and I'm really not sure if this is unlocking any new power, or is just isomorphic to a using newtype like `ReaderT (String -> m ()) m a`. Cheers :)

**Comment by mitchellwrosen** [comment]
Ah, I just read in the readme the typeclass-based carriers are actually a feature, as they are what make fusion possible.

**Comment by robrix** [comment]
> Ah, I just read in the readme the typeclass-based carriers are actually a feature, as they are what make fusion possible.

Yep, exactly!

That’s a neat use of `reflection`, but you can actually get this behaviour a little more prosaically by using a higher-order function as an argument to the carrier:

```haskell
newtype TraceC m a = TraceC { runTraceC :: (String -> m ()) -> m a }

runTrace :: Carrier sig m => (String -> m ()) -> Eff (TraceC m) a -> m a
runTrace f = runTraceC f . interpret
```

(For a more involved example, see `Control.Effect.Resumable`; this is pretty much what `runResumableWith`/`ResumableWithC` is doing.)

This definitely reduces boilerplate! However, by using a higher-order function, you’re cheating yourself out of efficiency—the compiler is much less able/willing to fuse, inline, and optimize away the interpreter.

That’s essentially the tradeoff that `fused-effects` makes: a little more code to write a new effect handler, but extremely efficient execution once you have done so. As you found, and as demonstrated above, it can also express reduced-boilerplate implementations, but my personal feeling is that they don’t belong in this library.

On the other hand, for quick experiments, you could always try a carrier something like this:

```haskell
newtype InterpreterC eff m a = InterpreterC { runInterpreterC :: (forall x . eff m (m x) -> m x) -> m a }

instance Carrier sig m => Carrier (eff :+: sig) (InterpreterC eff m) where
  …
```

I’m not certain how to adapt the above to express carriers like `StateC` or `ErrorC` that wrap results in a functor, but it could probably be done.

**Comment by robrix** [comment]
I’m going to close this out now for tidiness, but thank you for sharing your use of `reflection`!
