### ISSUE TITLE
runCut creates exponential right-nested branches

### ISSUE THREAD

**Issue by robrix** [robrix/fused-effects#65]
`runCut` interprets `NonDet` into an underlying `Alternative` in a way that ends up creating exponential numbers of right-nested branches. Therefore, the problem doesn’t show up with `runNonDetOnce`, as it terminates immediately on finding a solution in a left-to-right search, but with `runNonDet` (which explores the entire search space) it’s quite apparent.

**Comment by robrix** [comment]
Unfortunately, I think this means that we have to couple `Cut` carriers with search strategies. In particular, while it’s possible to use `runCut` with `runNonDetOnce` without accruing this cost (because the right-nested branches are never explored), it isn’t possible to compose it with `runNonDet` without paying this penalty.

An alternative carrier for `Cut` which explores all branches is possible, and can then be reinterpreted into some other `Alternative` instance, but you can’t compose this with `runNonDetOnce` to limit the search; since it has to explore the branches, their effects end up being performed:

```haskell
λ runM (runTraceByPrinting (runNonDetOnce (runCutAll (pure 'a' <|> trace "hello" *> pure 'b'))))
hello
"a"
```

**Comment by robrix** [comment]
I was mistaken—we just need to represent actual branches in `Branch`.

**Comment by zenzike** [comment]
For lots of related strategies, see “Heuristics Entwined with Handlers Combined. Tom Schrijvers and Nicolas Wu and Benoit Desouter and Bart Demoen.”

**Comment by robrix** [comment]
@zenzike: Thank you! I’m really enjoying that paper ❤️

**Comment by zenzike** [comment]
I usually distinguish between `cut` and `call`, where `cut` signals that siblings that proceed it under a `call` need to be removed, and `cull`, which picks only the first child in `p`

**Comment by robrix** [comment]
@zenzike: That’s super interesting. I kind of think that suggests we should hold off on releasing 0.1.2.0 until we’ve explored that.

**Comment by zenzike** [comment]
Right. You can only do that sort of thing if alternation is a deep embedding. I usually define:
```
data Nondet k = Or k k
```
specifically for that purpose.
