### ISSUE TITLE
Helper macro for writing concrete effect signatures

### ISSUE THREAD

**Issue by patrickt** [robrix/fused-effects#73]
One of the syntactic compromises of fused-effects compared to @joshvera/effects is that details about the carriers leak into concrete Eff types:

```
type Something
   = Eff (StateC [Foo]
   ( Eff (ErrorC SomeException
   ( Eff VoidC))))
```

We could make a Template Haskell splice that could generate the above from some shorthand notation like this:
```
type Something = [effects | [State [Foo], Error SomeException] |]
```

**Comment by JaSpa** [comment]
I think you don't need Template Haskell for this but the same can be accomplished by using type families and data kinds:

```haskell
type family StackEff (members :: [(* -> *) -> * -> *]) where
  StackEff '[] = Eff VoidC
  StackEff (m ': ms) = Eff (m (StackEff ms))

type family StackEffM (members :: [(* -> *) -> * -> *]) m where
  StackEffM '[] m' = Eff (LiftC m')
  StackEffM (m ': ms) m' = Eff (m (StackEffM ms m'))

-- 'Something' from @patrickt above
type Something = StackEff [StateC [Foo], ErrorC SomeException]
```

**Comment by robrix** [comment]
I’d argue that this isn’t an inappropriate leak of details. Your selection of a handler nails the computation down to a specific carrier, and thence semantics; that’s something consumers need to know about.

Further, this sort of specification is only necessary when you’re actually handling effects. In all other cases you can use `Member` constraints to abstract a computation over the carrier.

Finally, there isn’t in general a strong match between an effect and one specifically “blessed” carrier. Take `Trace`, for example.

If we want to be able to change the definitions or names of carriers without affecting consumers, we can always define type synonyms for them. But `newtype`s are cheap, so we won’t gain much by doing so in my opinion.

**Comment by robrix** [comment]
@patrickt: I’m going to close this out given the above, but feel free to reopen if necessary.

**Comment by patrickt** [comment]
@robrix Very fair! And @JaSpa’s example of how to infer it is lovely. Let’s keep this closed.
